language: go

go:
  - 1.5
  - 1.6

install:
  - make tools
  - make deps

script:
  - make test

after_script:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=traffic.coverprofile -service=travis-ci